ind=["Oil & Gas Production",
"Motor Vehicles",
"Accident &Health Insurance",
"Other Pharmaceuticals",
"Diversified Electronic Products",
"Metal Fabrications",
"Pollution Control Equipment",
"Ordnance And Accessories",
"Electronic Components",
"Major Chemicals",
"Containers/Packaging",
"Hotels/Resorts",
"Coal Mining",
"Investment Bankers/Brokers/Service",
"Biotechnology: Biological Products (No Diagnostic Substances)",
"Multi-Sector Companies",
"Trucking Freight/Courier Services",
"Plastic Products",
"RETAIL: Building Materials",
"Shoe Manufacturing",
"Food Chains",
"Industrial Machinery/Components",
"Wholesale Distributors",
"Consumer Electronics/Appliances",
"Biotechnology: Pharmaceutical Preparations",
"Broadcasting",
"Interactive Media",
"Biotechnology: In Vitro & In Vivo Diagnostic Substances",
"Auto & Home Supply Stores",
"Biotechnology: Laboratory Analytical Instruments",
 "Medicinal Chemicals and Botanical Products ",
"Professional Services",
"Forest Products",
"Biotechnology: Electromedical & Electrotherapeutic Apparatus",
"Diversified Commercial Services",
"Banks",
"Business Services",
"Other Specialty Stores",
"Life Insurance",
"Computer Manufacturing",
"Natural Gas Distribution",
"Aerospace",
"Construction Materials",
"Service to the Health Industry",
"Movies/Entertainment",
"Electrical Products",
"Hospital/Nursing Management",
"Specialty Chemicals",
"Publishing",
"Misc Health and Biotechnology Services",
"EDP Services",
"Railroads",
"Precious Metals",
"Other Metals and Minerals",
"Computer Communications Equipment",
"Durable Goods",
"Managed Health Care",
"Retail-Auto Dealers and Gas Stations",
"Savings Institutions",
"Specialty Foods",
"Retail: Computer Software & Peripheral Equipment",
"Transportation Services",
"Electronics Distribution",
"Electric Utilities: Central",
"Major Banks",
"Medical/Dental Instruments",
"Radio And Television Broadcasting And Communications Equipment",
"Trusts Except Educational Religious and Charitable",
"Industrial Specialties",
"EDP Peripherals",
"Medical/Nursing Services",
"Package Goods/Cosmetics",
"Catalog/Specialty Distribution",
"Auto Manufacturing",
"Commercial Banks",
"Office Equipment/Supplies/Services",
"Computer peripheral equipment",
"Finance: Consumer Services",
"Retail-Drug Stores and Proprietary Stores",
"Beverages (Production/Distribution)",
"Real Estate",
"Air Freight/Delivery Services",
"Power Generation",
"Textiles",
"Security Systems Services",
"Finance Companies",
"Cable & Other Pay Television Services",
"Engineering & Construction",
"Automotive Aftermarket",
"Telecommunications Equipment",
"Services-Misc. Amusement & Recreation",
"Farming/Seeds/Milling",
"Finance/Investors Services",
"Marine Transportation",
"Restaurants",
"Food Distributors",
"Home Furnishings",
"Consumer Specialties",
"Real Estate Investment Trusts",
"Assisted Living Services",
"Newspapers/Magazines",
"Computer Software: Programming Data Processing",
"Oilfield Services/Equipment",
"Homebuilding",
"Diversified Financial Services",
"Fluid Controls",
"Apparel",
"Water Sewer Pipeline Comm & Power Line Construction",
"Recreational Games/Products/Toys",
"Building Products",
"Packaged Foods",
"Tools/Hardware",
"Precision Instruments",
"Oil Refining/Marketing",
"Steel/Iron Ore",
"Property-Casualty Insurers",
"Auto Parts:O.E.M.",
"Building Materials",
"Military/Government/Technical",
"Metal Mining",
"Rental/Leasing Companies",
"Tobacco",
"Internet and Information Services",
"Miscellaneous manufacturing industries",
"Investment Managers",
"Consumer Electronics/Video Chains",
"Advertising",
"Paper",
"Ophthalmic Goods",
"Paints/Coatings",
"Department/Specialty Retail Stores",
"Aluminum",
"Computer Software: Prepackaged Software",
"Books",
"Specialty Insurers",
"Biotechnology: Commercial Physical & Biological Resarch",
"Beverages - Non-Alcoholic",
"Agricultural Chemicals",
"Environmental Services",
"Medical Specialities",
"Other Consumer Services",
"Pharmaceuticals and Biotechnology",
"Integrated oil Companies",
"Clothing/Shoe/Accessory Stores",
"Construction/Ag Equipment/Trucks",
"Diversified Manufacture",
"Meat/Poultry/Fish",
"Building operators",
"Semiconductors",
"Water Supply",
"Oil/Gas Transmission",
"Medical Electronics",]

ndTName=["OilGasProduction",
"MotorVehicles",
"AccidentHealthInsurance",
"OtherPharmaceuticals",
"DiversifiedElectronicProducts",
"MetalFabrications",
"PollutionControlEquipment",
"OrdnanceAndAccessories",
"ElectronicComponents",
"MajorChemicals",
"ContainersPackaging",
"HotelsResorts",
"CoalMining",
"InvestmentBankersBrokrsService",
"BiotechnologyBiologicalProducts",
"Multi-SectorCompanies",
"TruckingFreightCourierServices",
"PlasticProducts",
"RETAILBuildingMaterials",
"ShoeManufacturing",
"FoodChains",
"IndustrialMachineryComponents",
"WholesaleDistributors",
"ConsumerElectronicsAppliances",
"BiotechnologyPharmaceuticalPreparations",
"Broadcasting",
"InteractiveMedia",
"BiotechnologyInVitroInVivoDiagnosticSubstances",
"AutoHomeSupplyStores",
"BiotechnologyLaboratoryAnalyticalInstruments",
"MedicinalChemicalsandBotanicalProducts",
"ProfessionalServices",
"ForestProducts",
"BiotechnologyElectromedicalElectrotherapeuticApparatus",
"DiversifiedCommercialServices",
"Banks",
"BusinessServices",
"OtherSpecialtyStores",
"LifeInsurance",
"ComputerManufacturing",
"NaturalGasDistribution",
"Aerospace",
"ConstructionMaterials",
"ServicetotheHealthIndustry",
"MoviesEntertainment",
"ElectricalProducts",
"HospitalNursingManagement",
"SpecialtyChemicals",
"Publishing",
"MiscHealthandBiotechnologyServices",
"EDPServices",
"Railroads",
"PreciousMetals",
"OtherMetalsandMinerals",
"ComputerCommunicationsEquipment",
"DurableGoods",
"ManagedHealthCare",
"Retail-AutoDealersandGasStations",
"SavingsInstitutions",
"SpecialtyFoods",
"RetailComputerSoftwarePeripheralEquipment",
"TransportationServices",
"ElectronicsDistribution",
"ElectricUtilitiesCentral",
"MajorBanks",
"MedicalDentalInstruments",
"RadioAndTelevisionBroadcastingAndCommunicationsEquipment",
"TrustsExceptEducationalReligiousandCharitable",
"IndustrialSpecialties",
"EDPPeripherals",
"MedicalNursingServices",
"PackageGoodsCosmetics",
"CatalogSpecialtyDistribution",
"AutoManufacturing",
"CommercialBanks",
"OfficeEquipmentSuppliesServices",
"Computerperipheralequipment",
"FinanceConsumerServices",
"Retail-DrugStoresandProprietaryStores",
"Beverages(ProductionDistribution)",
"RealEstate",
"AirFreightDeliveryServices",
"PowerGeneration",
"Textiles",
"SecuritySystemsServices",
"FinanceCompanies",
"CableOtherPayTelevisionServices",
"EngineeringConstruction",
"AutomotiveAftermarket",
"TelecommunicationsEquipment",
"Services-Misc.AmusementRecreation",
"FarmingSeedsMilling",
"FinanceInvestorsServices",
"MarineTransportation",
"Restaurants",
"FoodDistributors",
"HomeFurnishings",
"ConsumerSpecialties",
"RealEstateInvestmentTrusts",
"AssistedLivingServices",
"NewspapersMagazines",
"ComputerSoftwareProgrammingDataProcessing",
"OilfieldServicesEquipment",
"Homebuilding",
"DiversifiedFinancialServices",
"FluidControls",
"Apparel",
"WaterSewerPipelineCommPowerLineConstruction",
"RecreationalGamesProductsToys",
"BuildingProducts",
"PackagedFoods",
"ToolsHardware",
"PrecisionInstruments",
"OilRefiningMarketing",
"SteelIronOre",
"Property-CasualtyInsurers",
"AutoPartsO.E.M.",
"BuildingMaterials",
"MilitaryGovernmentTechnical",
"MetalMining",
"RentalLeasingCompanies",
"Tobacco",
"InternetandInformationServices",
"Miscellaneousmanufacturingindustries",
"InvestmentManagers",
"ConsumerElectronicsVideoChains",
"Advertising",
"Paper",
"OphthalmicGoods",
"PaintsCoatings",
"DepartmentSpecialtyRetailStores",
"Aluminum",
"ComputerSoftwarePrepackagedSoftware",
"Books",
"SpecialtyInsurers",
"BiotechnologyCommercialPhysicalBiologicalResarch",
"Beverages-Non-Alcoholic",
"AgriculturalChemicals",
"EnvironmentalServices",
"MedicalSpecialities",
"OtherConsumerServices",
"PharmaceuticalsandBiotechnology",
"IntegratedoilCompanies",
"ClothingShoeAccessoryStores",
"ConstructionAgEquipmentTrucks",
"DiversifiedManufacture",
"MeatPoultryFish",
"Buildingoperators",
"Semiconductors",
"WaterSupply",
"OilGasTransmission",
"MedicalElectronics",]

sector=["Health Care",
"Finance",
"Consumer Staples",
"Real Estate",
"Basic Materials",
"Miscellaneous",
"Energy",
"Industrials",
"Utilities",
"Consumer Discretionary",
"Technology",
"Telecommunications"]