candlestick_patterns = {
    'CDL2CROWS':'Two Crows', 
    'CDL3BLACKCROWS':'Three Black Crows',
    'CDL3INSIDE':'Three Inside Up/Down',
    'CDL3LINESTRIKE':'Three-Line Strike',
    'CDL3OUTSIDE':'Three Outside Up/Down',
    'CDL3STARSINSOUTH':'Three Stars In The South',
    'CDLABANDONEDBABY':'Abandoned Baby',
    'CDLADVANCEBLOCK':'Advance Block',
    'CDLBELTHOLD':'Belt-hold',
    'CDLBREAKAWAY':'Breakaway',
    'CDLCLOSINGMARUBOZU':'Closing Marubozu',
    'CDLCOUNTERATTACK':'Counterattack',
    'CDLDARKCLOUDCOVER':'Dark Cloud Cover',
    'CDLDOJI':'Doji',
    'CDLDOJISTAR':'Doji Star',
    'CDLDRAGONFLYDOJI':'Dragonfly Doji',
    'CDLENGULFING':'Engulfing Pattern',
    'CDLEVENINGDOJISTAR':'Evening Doji Star',
    'CDLEVENINGSTAR':'Evening Star',
    'CDLGAPSIDESIDEWHITE':'Up/Down-gap side-by-side white lines',
    'CDLGRAVESTONEDOJI':'Gravestone Doji',
    'CDLHAMMER':'Hammer',
    'CDLHANGINGMAN':'Hanging Man',
    'CDLHARAMI':'Harami Pattern',
    'CDLHARAMICROSS':'Harami Cross Pattern',
    'CDLHIKKAKE':'Hikkake Pattern',
    'CDLHIKKAKEMOD':'Modified Hikkake Pattern',
    'CDLHOMINGPIGEON':'Homing Pigeon',
    'CDLINNECK':'In-Neck Pattern',
    'CDLKICKING':'Kicking',
    'CDLLADDERBOTTOM':'Ladder Bottom',
    'CDLLONGLEGGEDDOJI':'Long Legged Doji',
    'CDLLONGLINE':'Long Line Candle',
    'CDLMARUBOZU':'Marubozu',
    'CDLMATCHINGLOW':'Matching Low',
    'CDLMATHOLD':'Mat Hold',
    'CDLMORNINGDOJISTAR':'Morning Doji Star',
    'CDLMORNINGSTAR':'Morning Star',
    'CDLONNECK':'On-Neck Pattern',
    'CDLPIERCING':'Piercing Pattern',
    'CDLRICKSHAWMAN':'Rickshaw Man',
    'CDLRISEFALL3METHODS':'Rising/Falling Three Methods',
    'CDLSHOOTINGSTAR':'Shooting Star',
    'CDLSHORTLINE':'Short Line Candle',
    'CDLSPINNINGTOP':'Spinning Top',
    'CDLSTALLEDPATTERN':'Stalled Pattern',
    'CDLSTICKSANDWICH':'Stick Sandwich',
    'CDLTASUKIGAP':'Tasuki Gap',
    'CDLTHRUSTING':'Thrusting Pattern',
    'CDLTRISTAR':'Tristar Pattern',
    'CDLUPSIDEGAP2CROWS':'Upside Gap Two Crows',
    'CDLXSIDEGAP3METHODS':'Upside/Downside Gap Three Methods'
}

candlestick_patterns_urls = {
    'CDL2CROWS':'https://www.investopedia.com/terms/u/upside-gap-two-crows.asp', 
    'CDL3BLACKCROWS':'https://www.investopedia.com/terms/t/three_black_crows.asp',
    'CDL3INSIDE':'https://www.investopedia.com/terms/t/three-inside-updown.asp',
    'CDL3LINESTRIKE':'https://www.investopedia.com/articles/active-trading/092315/5-most-powerful-candlestick-patterns.asp#toc-three-line-strike',
    'CDL3OUTSIDE':'https://www.investopedia.com/terms/t/three-outside-updown.asp',
    'CDL3STARSINSOUTH':'https://www.investopedia.com/terms/t/three-stars-south.asp',
    'CDLABANDONEDBABY':'https://www.investopedia.com/terms/b/bullish-abandoned-baby.asp',
    'CDLADVANCEBLOCK':'https://www.investopedia.com/terms/a/advance-block.asp',
    'CDLBELTHOLD':'https://www.investopedia.com/terms/b/bullishbelthold.asp',
    'CDLBREAKAWAY':'https://www.investopedia.com/terms/b/breakawaygap.asp',
    'CDLCLOSINGMARUBOZU':'https://www.investopedia.com/stock-analysis/cotd/pot20120801.aspx',
    'CDLCOUNTERATTACK':'https://www.investopedia.com/terms/c/counterattack.asp',
    'CDLDARKCLOUDCOVER':'https://www.investopedia.com/terms/d/darkcloud.asp',
    'CDLDOJI':'https://www.investopedia.com/terms/d/doji.asp',
    'CDLDOJISTAR':'https://www.investopedia.com/terms/m/morningstar.asp',
    'CDLDRAGONFLYDOJI':'https://www.investopedia.com/terms/d/dragonfly-doji.asp',
    'CDLENGULFING':'https://www.investopedia.com/terms/b/bullishengulfingpattern.asp',
    'CDLEVENINGDOJISTAR':'https://www.investopedia.com/terms/m/morningstar.asp',
    'CDLEVENINGSTAR':'https://www.investopedia.com/terms/e/eveningstar.asp',
    'CDLGAPSIDESIDEWHITE':'https://www.investopedia.com/terms/u/updown-gap-sidebyside-white-lines.asp',
    'CDLGRAVESTONEDOJI':'https://www.investopedia.com/terms/g/gravestone-doji.asp',
    'CDLHAMMER':'https://www.investopedia.com/terms/h/hammer.asp',
    'CDLHANGINGMAN':'https://www.investopedia.com/articles/active-trading/040914/understanding-hanging-man-optimistic-candlestick-pattern.asp',
    'CDLHARAMI':'https://www.investopedia.com/terms/h/haramicross.asp',
    'CDLHARAMICROSS':'https://www.investopedia.com/terms/h/haramicross.asp',
    'CDLHIKKAKE':'https://www.investopedia.com/terms/h/hikkakepattern.asp',
    'CDLHIKKAKEMOD':'https://www.investopedia.com/terms/m/modified-hikkake-pattern.asp',
    'CDLHOMINGPIGEON':'https://www.investopedia.com/terms/b/bullishhomingpigeon.asp',
    'CDLINNECK':'https://www.investopedia.com/terms/n/neck-pattern.asp',
    'CDLKICKING':'https://www.investopedia.com/terms/k/kickingthetires.asp',
    'CDLLADDERBOTTOM':'https://www.investopedia.com/terms/l/ladder-bottom.asp',
    'CDLLONGLEGGEDDOJI':'https://www.investopedia.com/terms/l/long-legged-doji.asp',
    'CDLLONGLINE':'https://www.investopedia.com/terms/s/short-line-candle.asp',
    'CDLMARUBOZU':'https://www.investopedia.com/stock-analysis/cotd/pot20120801.aspx',
    'CDLMATCHINGLOW':'https://www.investopedia.com/terms/m/matching-low.asp',
    'CDLMATHOLD':'https://www.investopedia.com/terms/m/mat-hold-pattern.asp',
    'CDLMORNINGDOJISTAR':'https://www.investopedia.com/terms/m/morningstar.asp',
    'CDLMORNINGSTAR':'https://www.investopedia.com/terms/m/morningstar.asp',
    'CDLONNECK':'https://www.investopedia.com/terms/n/neck-pattern.asp',
    'CDLPIERCING':'https://www.investopedia.com/terms/piercing-pattern.asp',
    'CDLRICKSHAWMAN':'https://www.investopedia.com/terms/r/rickshaw-man.asp',
    'CDLRISEFALL3METHODS':'https://www.investopedia.com/terms/r/rising-three-methods.asp',
    'CDLSHOOTINGSTAR':'https://www.investopedia.com/terms/s/shootingstar.asp',
    'CDLSHORTLINE':'https://www.investopedia.com/terms/s/short-line-candle.asp',
    'CDLSPINNINGTOP':'https://www.investopedia.com/terms/s/spinning-top.asp',
    'CDLSTALLEDPATTERN':'https://www.investopedia.com/terms/s/stalled-pattern.asp',
    'CDLSTICKSANDWICH':'https://www.investopedia.com/terms/s/stick-sandwich.asp',
    'CDLTASUKIGAP':'https://www.investopedia.com/terms/u/upside-tasuki-gap.asp',
    'CDLTHRUSTING':'https://www.investopedia.com/terms/t/thrusting-pattern.asp',
    'CDLTRISTAR':'https://www.investopedia.com/terms/t/tri-star.asp',
    'CDLUPSIDEGAP2CROWS':'https://www.investopedia.com/terms/u/upside-gap-two-crows.asp',
    'CDLXSIDEGAP3METHODS':'https://www.investopedia.com/terms/u/upsidedownside-gap-three-methods.asp'
}